object Versions {

    const val gradle = "7.1.0-alpha02"
    const val kotlin_version = "1.5.30"
    const val hilt_version = "2.37"
    const val appcompat = "1.3.1"
    const val core_ktx = "1.6.0"
    const val fragment = "1.3.6"
    const val android_support_annotations = "28.0.0"
    const val lifecycle_viewmodel_savedstate = "2.3.1"
    const val annotation_jsr250_api = "1.0"
    const val okhttp = "4.9.1"
    const val apollo = "2.1.0"
    const val coroutines = "1.4.2"
    const val constraint_layout = "2.0.4"
    const val recyclerview = "1.2.1"
    const val glide = "4.12.0"
    const val timber = "4.7.1"
    const val lottie = "3.7.0"
    const val jetbrains_annotation = "16.0.1"
    const val assisted_inject_annotations_dagger = "0.5.2"
    const val junit = "4.13.2"
    const val android_test_runner = "1.4.0"
    const val espresso_core = "3.4.0"

}
