object Versions {

    const val gradle = "7.1.0-alpha02"
    const val kotlin_version = "1.6.0"
    const val hilt_version = "2.43.2"
    const val appcompat = "1.4.1"
    const val core_ktx = "1.9.0"
    const val fragment = "1.5.2"
    const val android_support_annotations = "28.0.0"
    const val lifecycle_viewmodel_savedstate = "2.5.1"
    const val annotation_jsr250_api = "1.0"
    const val okhttp = "4.9.3"
    const val apollo = "2.5.11"
    const val coroutines = "1.6.4"
    const val constraint_layout = "2.1.3"
    const val recyclerview = "1.2.1"
    const val glide = "4.12.0"
    const val timber = "4.7.1"
    const val lottie = "5.0.3"
    const val jetbrains_annotation = "16.0.1"
    const val assisted_inject_annotations_dagger = "0.8.1"
    const val junit = "5.8.2"
    const val android_test_runner = "1.4.0"
    const val espresso_core = "3.4.0"

}
